stanfordnmbl/opencap-api

- mcserver/migrations/0010_auto_20230202_1908.py
- mcserver/migrations/0011_auto_20230203_1355.py
- mcserver/migrations/0011_rename_profesion_user_profession.py
I had a problem locally with launching the pulled code due to the conflicting migrations. This is because of merging different branches with their migrations. Please check the fixes.
> fixed conflicting migrations

- mcserver/admin.py
- mcserver/forms.py
- mcserver/models.py
- mcserver/serializers.py
- mcserver/templates/admin/set_subject.html
- Subjects data duplicates to `Session.meta` attribute
- Added "Set subject" action to the Session interface in admin
> Backward compatibility for Subjects

- mcserver/views.py
- necessary fix for loading valid sessions for specified subject
> Subject filtering for valid sessions api

- mcserver/serializers.py
- mcserver/views.py
for direct-to-s3 result uploading. Same thing we did to the phones
> add media_url

- mcserver/views.py
> WIP - Detecting frozen/disconnected/missing phones

- mcserver/views.py
Reverts stanfordnmbl/opencap-api#44
> Revert "WIP - Detecting frozen/disconnected/missing phones"

- mcserver/serializers.py
- mcserver/views.py
@suhlrich I had to create a new PR. Please make sure that it is the only things that you needed to add.
> Enable results straight to S3

- mcserver/views.py
tested locally and it works fine
FYI @antoinefalisse
> add priority processing groups to the queue

- mcserver/views.py
To be merged with https://github.com/stanfordnmbl/opencap-viewer/pull/121
> Session Name

- mcserver/views.py
> solve the redundant video model problem

- mcserver/views.py
@AlbertoCasasOrtiz reverting this for now
Reverts stanfordnmbl/opencap-api#112
> Revert "Num connected phones updated"

- mcserver/views.py
Reverts stanfordnmbl/opencap-api#113
> Revert "Revert "Num connected phones updated""

- mcserver/views.py
Reverts stanfordnmbl/opencap-api#118
> Re-merge n_connected_phones

- mcserver/views.py
Reverts stanfordnmbl/opencap-api#121
> Revert "Checking if video exists in video database before checking if url exists."

- mcserver/views.py
Reverts stanfordnmbl/opencap-api#120
> Revert "Re-merge n_connected_phones"

- mcserver/views.py
Reverts stanfordnmbl/opencap-api#123
> Revert "Revert "Re-merge n_connected_phones""

- mcserver/views.py
Reverts stanfordnmbl/opencap-api#122
> Revert "Revert "Checking if video exists in video database before checking if url exists.""

- mcserver/views.py
Fix for https://github.com/stanfordnmbl/opencap-api/issues/92
> Allow download for public sessions

- mcserver/views.py
Fix for https://github.com/stanfordnmbl/opencap-api/issues/60
> Result upload permissions

- mcserver/serializers.py
- mcserver/views.py
Reverts stanfordnmbl/opencap-api#176
> Revert "Optimization fixes"

- mcserver/serializers.py
- mcserver/views.py
Reverts stanfordnmbl/opencap-api#177
> Revert "Revert "Optimization fixes""

- mcserver/models.py
- mcserver/views.py
Reverts stanfordnmbl/opencap-api#191
> Revert "Admin subjects + public analysis sharing"

- mcserver/models.py
- mcserver/views.py
Reverts stanfordnmbl/opencap-api#193
> Revert "Revert "Revert "Admin subjects + public analysis sharing"""

- mcserver/models.py
- mcserver/views.py
Reverts stanfordnmbl/opencap-api#194
> Revert "Revert "Revert "Revert "Admin subjects + public analysis sharing""""

- mcserver/serializers.py
This must be merged with https://github.com/stanfordnmbl/opencap-viewer/pull/346
> Allowing change email.

- mcserver/settings.py
- mcserver/urls.py
- requirements.txt
- Graphviz for ERD database diagram.
- Swagger for API documentation.
> Added resources for API and database documentation.

- mcserver/admin.py
shorten some column names and clean up duration formatting
> dev: reduce processed fields clutter in list view

- mcserver/models.py
- mcserver/views.py
The labels for subjects on django looked up to date on dev, so I think this is good to merge to main.
> Dev into main

- mcserver/views.py
> Adding fix from #164.

- mcserver/models.py
- mcserver/views.py
I tested it myself in dev and was working properly.
> Dev->Main - Solved issue with child sessions not having callibration trial if parent removed.

- mcserver/views.py
Reverts stanfordnmbl/opencap-api#251
> Revert "Mono dequeue"

- mcserver/tasks.py
- mcserver/zipsession_v2.py
Addresses #264 (and some other similar functions).
There are a few filesystem-related calls that intermittently show up as errors on sentry (`shutil.rmtree()`, `ZipFile.write()`, `os.remove()`) possibly due to blips in ECS local storage. This PR allows some quick retries to get around these.
Testing was done by setting up a local viewer and API and seeing that the Download Data button worked to retrieve zipped data.
> dev: retry filesystem calls during download session data

- mcserver/settings.py
- mcserver/tasks.py
- mcserver/zipsession_v2.py
Includes improvements to Download Data from the web app. Tested by downloading previously collected data on the dev server.
> main: download data improvements

- mcserver/zipsession_v2.py
Working on dev, successfully downloaded a session.
> main <- dev
